clear; close all; clc; dbstop if error;

registre = struct('adresse', [], ...
                  'format', [], ...
                  'type', [], ...
                  'nom', [], ...
                  'altitude', [], ...
                  'timeFlag', [], ...
                  'cprFlag', [], ...
                  'latitude', [], ...
                  'longitude', [], ...
                  'trajectoire', []);
load('adsb_msgs.mat'); 
[n,m] = size(adsb_msgs);
for i = 1:m
    registre = bit2registre(registre, adsb_msgs(:,i));
end