clear; close all; clc; dbstop if error;

registre = struct('adrese', [], ...
                  'format', [], ...
                  'type', [], ...
                  'nom', [], ...
                  'altitude', [], ...
                  'timeFlag', [], ...
                  'cprFlag', [], ...
                  'latitude', [], ...
                  'longitude', [], ...
                  'trajectoire', []);
load('adsb_msgs.mat'); 
registre = bit2registre(registre, adsb_msgs(:,1)); % 25 et 12 identification
